import { createHash } from "crypto";
import { streamText } from "ai";
import { aiAvailable } from "@/lib/ai/provider";
import { userSmartModel } from "@/lib/ai/user-model";
import { requireUser } from "@/lib/auth";
import { checkRateLimit } from "@/lib/rate-limit";
import { checkAiBudget, recordAiUsage, budgetExceededMessage } from "@/lib/ai/budget";
import { getMatchingBrief, saveUserBrief } from "@/lib/brief-cache";
import { getUserSettings } from "@/lib/settings/store";
import {
  BRIEF_LEVEL_CONFIG,
  DEFAULT_BRIEF_LEVEL,
  findSection,
  isBriefLevel,
  planBrief,
  type BriefLevel,
} from "@/lib/today/brief-plan";
import {
  sectionArticleBlock,
  sectionMaxTokens,
  sectionPreamble,
  sectionSystemPrompt,
} from "@/lib/today/brief-prompts";
import {
  bodyCharLimit,
  briefFingerprint,
  briefSourceMap,
  fetchPlanRows,
  fetchSectionRows,
  queueLimit,
  stripHtml,
  toArticleInputs,
  toPlanArticles,
  unreadBriefIds,
} from "@/lib/today/brief-queue";
import type { BriefSourceRef } from "@/lib/db/schema";

export const runtime = "nodejs";
export const maxDuration = 60;

/**
 * The Daily Brief, generated one section at a time.
 *
 * ## Why sections
 *
 * This app is hosted on Netlify, where a function is killed at ~10s no matter
 * what `maxDuration` says (that export is Vercel-only). "Make the brief more
 * detailed" is therefore not a matter of asking one call for more words — a
 * longer single generation is exactly what the platform cannot finish, and it
 * fails with nothing on screen.
 *
 * So the brief is planned deterministically (no model — see
 * `src/lib/today/brief-plan.ts`) into a lead, a section per topic desk, and a
 * quick-clear list, and each section is generated by its own short request with
 * its own bounded slice of the queue and its own output ceiling. Total detail
 * goes up several-fold; per-request work goes DOWN. A section that fails costs
 * only that section, and retries on its own.
 *
 * Endpoints:
 *   GET  /api/brief            → cheap fingerprint of the unread set (drift check)
 *   GET  /api/brief?plan=1     → the section plan + source map, no model involved
 *   POST /api/brief            → generate ONE section (streamed)
 *   POST /api/brief {systemPrompt} → legacy single-pass brief with a custom prompt
 */

// Trailing markers appended after the text. The client splits on these and
// never renders them. Sources go in the body (not a header) because a 60-article
// map can exceed proxy header-size caps. Mirrors /api/ask.
// NOT exported — Next.js route modules only allow specific named exports.
const BRIEFSOURCES_SENTINEL = "<<<SB_BRIEFSOURCES:";
const USAGE_SENTINEL = "<<<SB_USAGE:";

// Raw full_text cap in SQL — ~6× the plain-text budget leaves HTML headroom.
const RAW_FULLTEXT_MULTIPLIER = 6;

/** The user's stored brief preferences, validated. */
async function briefPrefs(userId: string): Promise<{ level: BriefLevel; priority: string[] }> {
  try {
    const s = await getUserSettings(userId);
    return {
      level: isBriefLevel(s.briefLevel) ? s.briefLevel : DEFAULT_BRIEF_LEVEL,
      priority: Array.isArray(s.briefTopics) ? s.briefTopics.filter((t) => typeof t === "string") : [],
    };
  } catch {
    // A settings hiccup must not stop the brief — fall back to the defaults.
    return { level: DEFAULT_BRIEF_LEVEL, priority: [] };
  }
}

/**
 * GET /api/brief — cheap fingerprint of the current unread set (id-only, no
 * bodies, no model). The client compares it against the fingerprint stored with
 * its cached brief to show a "new articles — regenerate" nudge without paying
 * for a regeneration.
 *
 * GET /api/brief?plan=1 — additionally returns the section plan and the source
 * map. Still no model call: desks are keyword-classified, so the Today tab can
 * paint the whole outline (and every desk's item count) before generating
 * anything.
 */
export async function GET(req: Request) {
  let auth;
  try {
    auth = await requireUser();
  } catch {
    return new Response("Unauthorized", { status: 401 });
  }
  const userId = auth.user.id;
  const params = new URL(req.url).searchParams;
  const wantPlan = params.get("plan") === "1";

  if (!wantPlan) {
    const ids = await unreadBriefIds(userId, queueLimit(BRIEF_LEVEL_CONFIG.deep.articleLimit));
    return Response.json({ fingerprint: briefFingerprint(ids), count: ids.length });
  }

  const prefs = await briefPrefs(userId);
  // An explicit level wins over the stored one: the client passes the depth the
  // user just picked, so the plan doesn't lag a settings write by a round trip.
  const levelParam = params.get("level");
  const level = isBriefLevel(levelParam) ? levelParam : prefs.level;
  const priority = prefs.priority;
  const { rows, windowLabel } = await fetchPlanRows(
    userId,
    queueLimit(BRIEF_LEVEL_CONFIG[level].articleLimit),
  );
  const plan = planBrief(toPlanArticles(rows), { level, priority });
  return Response.json({
    fingerprint: briefFingerprint(rows.map((r) => r.id)),
    count: rows.length,
    windowLabel,
    level,
    priority,
    sections: plan.sections,
    desks: plan.desks,
    sources: briefSourceMap(rows),
  });
}

type PostBody = {
  /** A section key from the plan ("lead", "topic:ai", "skip"). */
  section?: string;
  level?: string;
  /** The fingerprint the client planned against, to catch drift. */
  fingerprint?: string;
  /** Legacy single-pass mode: the user's own framing for the whole brief. */
  systemPrompt?: string;
  force?: boolean;
};

export async function POST(req: Request) {
  let auth;
  try {
    auth = await requireUser();
  } catch {
    return new Response("Unauthorized", { status: 401 });
  }
  const user = auth.user;

  // A sectioned brief is several requests (up to ~8 at the deepest level), and
  // a user may regenerate or retry a section on top of that — hence a ceiling
  // per minute well above the old per-brief one.
  const rl = await checkRateLimit(user.id, "brief", 60, 60);
  if (!rl.allowed) {
    return new Response("Rate limit reached — wait a moment before regenerating the brief.", {
      status: 429,
    });
  }
  const budget = await checkAiBudget(user.id);
  if (!budget.allowed) {
    return new Response(budgetExceededMessage(budget), { status: 429 });
  }

  if (!aiAvailable()) {
    return new Response(
      "No AI provider configured. Add ANTHROPIC_API_KEY or OPENROUTER_API_KEY to your env vars to enable the Daily Brief.",
      { status: 503 },
    );
  }

  let body: PostBody = {};
  try {
    body = (await req.json()) as PostBody;
  } catch {
    // No body or invalid JSON — treat as a default sectioned request.
  }
  const customPrompt =
    typeof body.systemPrompt === "string" && body.systemPrompt.trim().length > 0
      ? body.systemPrompt.trim()
      : null;

  if (customPrompt) return legacyBrief(user.id, customPrompt, body.force === true, req);
  return sectionBrief(user.id, body, req);
}

/**
 * Generate one planned section. Small input, capped output: this is the request
 * shape that fits comfortably inside the hosting platform's function budget.
 */
async function sectionBrief(userId: string, body: PostBody, req: Request): Promise<Response> {
  const prefs = await briefPrefs(userId);
  const level = isBriefLevel(body.level) ? body.level : prefs.level;
  const cfg = BRIEF_LEVEL_CONFIG[level];
  const bodyChars = bodyCharLimit(cfg.bodyChars);

  const { rows, windowLabel } = await fetchSectionRows(
    userId,
    queueLimit(cfg.articleLimit),
    bodyChars * RAW_FULLTEXT_MULTIPLIER,
  );
  if (rows.length === 0) {
    return new Response(
      "No unread articles to brief on. Add some feeds and sync them, then come back.",
      { status: 422, headers: { "content-type": "text/plain; charset=utf-8" } },
    );
  }

  const fingerprint = briefFingerprint(rows.map((r) => r.id));
  // The client planned against a specific unread set. If a sync landed in
  // between, its [n] numbers no longer mean what it thinks — send it back to
  // re-plan rather than writing a section against shifted numbering.
  if (body.fingerprint && body.fingerprint !== fingerprint) {
    return Response.json({ error: "queue-changed", fingerprint }, { status: 409 });
  }

  const plan = planBrief(toPlanArticles(rows), { level, priority: prefs.priority });
  const section = body.section ? findSection(plan, body.section) : plan.sections[0];
  if (!section) {
    return new Response("No such brief section", { status: 404 });
  }

  const inputs = toArticleInputs(rows, section.refs);
  const deskCount = plan.desks.find((d) => d.topicId === section.topicId)?.count;
  const preamble = sectionPreamble(section, {
    windowLabel,
    totalCount: rows.length,
    deskCount,
  });

  const result = streamText({
    model: await userSmartModel(),
    system: sectionSystemPrompt(section, level),
    messages: [
      {
        role: "user",
        content: [
          {
            // Anthropic prompt caching: a retry of the same section — or the
            // same desk tomorrow, when most of the queue is unchanged — reuses
            // these tokens instead of re-paying for them.
            type: "text",
            text: `Articles for this section:\n${preamble}\n\n${sectionArticleBlock(section, inputs, level)}`,
            providerOptions: { anthropic: { cacheControl: { type: "ephemeral" } } },
          },
          { type: "text", text: `Write the "${section.label}" section now.` },
        ],
      },
    ],
    temperature: 0.4,
    maxTokens: sectionMaxTokens(section, level),
    abortSignal: req.signal,
  });

  const stream = streamWithUsage(result, userId, req);
  return new Response(stream, {
    headers: {
      "content-type": "text/plain; charset=utf-8",
      "x-brief-fingerprint": fingerprint,
      "x-brief-section": section.key,
    },
  });
}

/**
 * The pre-sectioned path, kept for users who wrote their own brief prompt: one
 * call, their framing, the whole queue. It can't be split into sections (only
 * the author knows what shape they asked for), so it also keeps the server-side
 * whole-brief cache that makes a reload free.
 */
async function legacyBrief(
  userId: string,
  systemPrompt: string,
  force: boolean,
  req: Request,
): Promise<Response> {
  const bodyChars = bodyCharLimit(BRIEF_LEVEL_CONFIG.standard.bodyChars);
  const { rows, windowLabel } = await fetchSectionRows(
    userId,
    queueLimit(BRIEF_LEVEL_CONFIG.standard.articleLimit),
    bodyChars * RAW_FULLTEXT_MULTIPLIER,
  );
  if (rows.length === 0) {
    return new Response(
      "No unread articles to brief on. Add some feeds and sync them, then come back.",
      { headers: { "content-type": "text/plain; charset=utf-8" } },
    );
  }

  const fingerprint = briefFingerprint(rows.map((r) => r.id));
  const sourceMap = briefSourceMap(rows);
  const promptHash = createHash("sha1").update(systemPrompt).digest("base64");

  if (!force) {
    const hit = await getMatchingBrief(userId, fingerprint, promptHash);
    if (hit) {
      const cached =
        `${hit.content}` +
        `\n${BRIEFSOURCES_SENTINEL}${JSON.stringify(hit.sourceMap)}` +
        `\n${USAGE_SENTINEL}${JSON.stringify(hit.usage)}`;
      return new Response(cached, {
        headers: {
          "content-type": "text/plain; charset=utf-8",
          "x-brief-fingerprint": fingerprint,
          "x-brief-cache": "hit",
        },
      });
    }
  }

  const articleBlock = rows
    .map((r, i) => {
      const text = r.fullText ? stripHtml(r.fullText) : r.excerpt ?? "";
      const trimmed = text.length > bodyChars ? `${text.slice(0, bodyChars)}…` : text;
      return `[${i + 1}] (${r.feedTitle}) ${r.title}\n${trimmed}`.trim();
    })
    .join("\n\n");

  const result = streamText({
    model: await userSmartModel(),
    system: systemPrompt,
    messages: [
      {
        role: "user",
        content: [
          {
            type: "text",
            text: `Articles to brief on:\n\n[Briefing window: ${windowLabel}, ${rows.length} unread articles]\n\n${articleBlock}`,
            providerOptions: { anthropic: { cacheControl: { type: "ephemeral" } } },
          },
          { type: "text", text: "Write the daily brief now." },
        ],
      },
    ],
    temperature: 0.4,
    abortSignal: req.signal,
  });

  const stream = streamWithUsage(result, userId, req, {
    sourceMap,
    onDone: (content, usage) => {
      if (!content.trim()) return;
      void saveUserBrief(userId, {
        fingerprint,
        promptHash,
        content,
        sourceMap: sourceMap as BriefSourceRef[],
        usage,
      });
    },
  });
  return new Response(stream, {
    headers: {
      "content-type": "text/plain; charset=utf-8",
      "x-brief-fingerprint": fingerprint,
    },
  });
}

type Usage = { promptTokens: number; completionTokens: number; totalTokens: number };

/**
 * Pipe the model's text through, then append the trailing sentinels the client
 * strips and parses. Sources/usage aren't known until generation finishes, so
 * they can't go in headers that were already sent.
 */
function streamWithUsage(
  result: ReturnType<typeof streamText>,
  userId: string,
  req: Request,
  opts: {
    sourceMap?: BriefSourceRef[];
    onDone?: (content: string, usage: Usage) => void;
  } = {},
): ReadableStream<Uint8Array> {
  const encoder = new TextEncoder();
  return new ReadableStream<Uint8Array>({
    async start(controller) {
      try {
        let acc = "";
        for await (const delta of result.textStream) {
          acc += delta;
          controller.enqueue(encoder.encode(delta));
        }
        if (opts.sourceMap) {
          controller.enqueue(
            encoder.encode(`\n${BRIEFSOURCES_SENTINEL}${JSON.stringify(opts.sourceMap)}`),
          );
        }
        const usage = await result.usage;
        const payload: Usage = {
          promptTokens: usage?.promptTokens ?? 0,
          completionTokens: usage?.completionTokens ?? 0,
          totalTokens: usage?.totalTokens ?? 0,
        };
        void recordAiUsage(userId, payload.totalTokens);
        controller.enqueue(encoder.encode(`\n${USAGE_SENTINEL}${JSON.stringify(payload)}`));
        opts.onDone?.(acc, payload);
      } catch (err) {
        if (!req.signal.aborted) {
          try {
            controller.enqueue(
              encoder.encode(
                `\n\n_(generation error: ${err instanceof Error ? err.message : "unknown"})_`,
              ),
            );
          } catch {
            /* controller closed */
          }
        }
      } finally {
        try {
          controller.close();
        } catch {
          /* already closed */
        }
      }
    },
  });
}
