import { streamText } from "ai";
import { aiAvailable } from "@/lib/ai/provider";
import { quietReasoningOptions, withReasoningHeadroom } from "@/lib/ai/models";
import { resolveUserSmartModel } from "@/lib/ai/user-model";
import { requireUser } from "@/lib/auth";
import { checkRateLimit } from "@/lib/rate-limit";
import { checkAiBudget, recordAiUsage, budgetExceededMessage } from "@/lib/ai/budget";
import { loadStoryMemory } from "@/lib/brief-cache";
import { getUserSettings } from "@/lib/settings/store";
import {
  BRIEF_LEVEL_CONFIG,
  DEFAULT_BRIEF_LEVEL,
  findSection,
  isBriefLevel,
  planBrief,
  type BriefLevel,
} from "@/lib/today/brief-plan";
import {
  normalizeCustomDesks,
  resolveDesks,
  topicLabel,
  type BriefTopic,
  type CustomDesk,
} from "@/lib/today/topics";
import {
  continuityBlock,
  externalBlock,
  readContextBlock,
  sectionArticleBlock,
  sectionMaxTokens,
  sectionPreamble,
  sectionSystemPrompt,
  storyBlock,
  threadBlock,
  normalizeBriefInstructions,
} from "@/lib/today/brief-prompts";
import {
  bodyCharLimit,
  briefFingerprint,
  briefOrderFingerprint,
  briefSourceMap,
  briefWhyMap,
  fetchBodies,
  fetchBriefQueue,
  fetchReadContext,
  queueLimit,
  scanLimit,
  toArticleInputs,
  toPlanArticles,
  unreadBriefIds,
} from "@/lib/today/brief-queue";
import { EMPTY_SECTION_HEADER, briefStream } from "@/lib/today/brief-stream";
import { loadDeskWeights } from "@/lib/today/feedback-store";
import { loadEngagedTitles, loadFeedTrust } from "@/lib/today/reading-signals";
import { followMatcher, normalizeFollowedStories, type FollowedStory } from "@/lib/today/story-follow";
import {
  isRuledOut,
  normalizeMisfiles,
  suggestDesks,
  type MisfiledStory,
} from "@/lib/today/desk-suggest";
import { loadExternalStories } from "@/lib/trending/signals";
import { TITLE_SHINGLE_THRESHOLD, jaccard, titleShingles } from "@/lib/trending/cluster";

export const runtime = "nodejs";
export const maxDuration = 60;

/**
 * The Daily Brief, generated one section at a time.
 *
 * ## Why sections
 *
 * The brief is planned deterministically (no model — see
 * `src/lib/today/brief-plan.ts`) into a lead, a section per topic desk, and a
 * quick-clear list, and each section is generated by its own request with its
 * own bounded slice of the queue and its own output ceiling.
 *
 * That shape was originally forced by a serverless host with a ~10s function
 * cap; it is kept on Railway because independent sections stream to the reader
 * as they land and fail independently. See `brief-plan.ts` for the full
 * reasoning.
 *
 * Endpoints:
 *   GET  /api/brief            → cheap fingerprint of the unread set (drift check)
 *   GET  /api/brief?plan=1     → the section plan + source map, no model involved
 *   POST /api/brief            → generate ONE section (streamed)
 *
 * There is no whole-brief mode. Customization used to replace the entire
 * generation with the reader's own prompt, which meant opting out of the plan
 * and everything built on it; it is now standing instructions layered into each
 * section's prompt instead — see `brief-prompts.ts`.
 */

// Raw full_text cap in SQL — ~6× the plain-text budget leaves HTML headroom.
const RAW_FULLTEXT_MULTIPLIER = 6;

/**
 * Already-read articles offered to a section as background. A dozen titles is
 * a few hundred tokens and covers a heavy morning's reading; more than that
 * starts competing for attention with the articles the section is actually
 * supposed to be writing about.
 */
const READ_CONTEXT_LIMIT = 12;

type BriefPrefs = {
  level: BriefLevel;
  priority: string[];
  /** The reader's own desks, validated. */
  customDesks: CustomDesk[];
  /** Those desks plus the built-ins — what every classifier here works from. */
  desks: BriefTopic[];
  /** The reader's standing instructions, applied to every section. */
  instructions: string;
  /** Stories the reader asked to stay on. */
  followedStories: FollowedStory[];
  /** Desks the reader has ruled out, story by story. */
  misfiles: MisfiledStory[];
};

/** The user's stored brief preferences, validated. */
async function briefPrefs(userId: string): Promise<BriefPrefs> {
  try {
    const s = await getUserSettings(userId);
    const customDesks = normalizeCustomDesks(s.customDesks);
    return {
      level: isBriefLevel(s.briefLevel) ? s.briefLevel : DEFAULT_BRIEF_LEVEL,
      priority: Array.isArray(s.briefTopics) ? s.briefTopics.filter((t) => typeof t === "string") : [],
      customDesks,
      desks: resolveDesks(customDesks),
      instructions: normalizeBriefInstructions(s.briefInstructions),
      followedStories: normalizeFollowedStories(s.followedStories),
      misfiles: normalizeMisfiles(s.briefMisfiles),
    };
  } catch {
    // A settings hiccup must not stop the brief — fall back to the defaults.
    return {
      level: DEFAULT_BRIEF_LEVEL,
      priority: [],
      customDesks: [],
      desks: resolveDesks(),
      instructions: "",
      followedStories: [],
      misfiles: [],
    };
  }
}

/**
 * Everything selection is scored by, beyond the queue itself.
 *
 * Assembled in one place because every caller that has to agree about `[n]` —
 * the plan, each section, the XP mapping, the drift check — must pass exactly
 * the same set. A signal loaded by one and forgotten by another would select a
 * different queue and shift every citation in the brief.
 */
async function selectionSignals(userId: string, prefs: BriefPrefs) {
  const [deskWeights, feedTrust] = await Promise.all([
    loadDeskWeights(userId),
    loadFeedTrust(userId),
  ]);
  return {
    priority: prefs.priority,
    desks: prefs.desks,
    deskWeights,
    feedTrust,
    isFollowed: followMatcher(prefs.followedStories),
    ruledOut: (title: string, deskId: string) => isRuledOut(title, deskId, prefs.misfiles),
  };
}

/**
 * GET /api/brief — cheap fingerprint of the current unread set (id-only, no
 * bodies, no model). The client compares it against the fingerprint stored with
 * its cached brief to show a "new articles — regenerate" nudge without paying
 * for a regeneration.
 *
 * GET /api/brief?plan=1 — additionally returns the section plan and the source
 * map. Still no model call: desks are keyword-classified, so the Today tab can
 * paint the whole outline (and every desk's item count) before generating
 * anything.
 */
export async function GET(req: Request) {
  let auth;
  try {
    auth = await requireUser();
  } catch {
    return new Response("Unauthorized", { status: 401 });
  }
  const userId = auth.user.id;
  const params = new URL(req.url).searchParams;
  const wantPlan = params.get("plan") === "1";

  const prefs = await briefPrefs(userId);
  // An explicit level wins over the stored one: the client passes the depth the
  // user just picked, so the plan doesn't lag a settings write by a round trip.
  const levelParam = params.get("level");
  const level = isBriefLevel(levelParam) ? levelParam : prefs.level;
  const priority = prefs.priority;
  const cfg = BRIEF_LEVEL_CONFIG[level];

  if (!wantPlan) {
    // Selection decides WHICH articles are the queue, so the drift check has to
    // run the same selection or it would compare two different sets and nudge
    // forever. It stops short of the excerpt fetch — ids are all it looks at.
    const ids = await unreadBriefIds(userId, {
      limit: queueLimit(cfg.articleLimit),
      scanLimit: scanLimit(cfg.scanLimit, cfg.articleLimit),
      ...(await selectionSignals(userId, prefs)),
    });
    return Response.json({ fingerprint: briefFingerprint(ids), count: ids.length });
  }

  // Signals first, and in parallel with everything that doesn't depend on them:
  // selection is scored by desk verdicts and feed trust, so the queue cannot be
  // fetched until they are in hand.
  const [signals, externals, memory, engagedTitles] = await Promise.all([
    selectionSignals(userId, prefs),
    // Fail-soft and independent: no trending run yet, or all four public
    // signals down, simply means no "outside your feeds" section today.
    cfg.externalPicks > 0
      ? loadExternalStories(EXTERNAL_CANDIDATE_POOL).catch(() => [])
      : Promise.resolve([]),
    loadStoryMemory(userId),
    loadEngagedTitles(userId),
  ]);
  const { rows, windowLabel, coverage, omitted, scanTitles, threads } = await fetchBriefQueue(
    userId,
    {
      limit: queueLimit(cfg.articleLimit),
      scanLimit: scanLimit(cfg.scanLimit, cfg.articleLimit),
      ...signals,
    },
  );
  const plan = planBrief(toPlanArticles(rows), {
    level,
    priority,
    externals: pickExternals(externals, scanTitles, priority),
    memory,
    deskWeights: signals.deskWeights,
    desks: prefs.desks,
    threads,
  });
  const ids = rows.map((r) => r.id);
  // Stories the queue did not reach, by desk, so the Today tab can say what was
  // left out rather than implying the brief saw everything.
  const omittedByDesk = new Map(omitted.map((o) => [o.topicId, o]));
  const deskRows = plan.desks.map((d) => ({
    ...d,
    omittedStories: omittedByDesk.get(d.topicId)?.stories ?? 0,
    omittedArticles: omittedByDesk.get(d.topicId)?.articles ?? 0,
  }));
  // A desk with nothing at all in the queue does not appear in the plan's desk
  // list, so a desk the budget skipped ENTIRELY would silently vanish from
  // "also unread, not written up" — the one line whose job is to admit it.
  const known = new Set(plan.desks.map((d) => d.topicId));
  for (const o of omitted) {
    if (known.has(o.topicId)) continue;
    deskRows.push({
      topicId: o.topicId,
      label: topicLabel(o.topicId, prefs.desks),
      count: 0,
      included: false,
      omittedStories: o.stories,
      omittedArticles: o.articles,
    });
  }
  // Which desk claimed each ref, from the plan's own buckets — the same answer
  // the desk sections were built from, not a second guess at it.
  const deskByRef = new Map<number, { id: string; label: string }>();
  for (const section of plan.sections) {
    if (section.kind !== "topic" || !section.topicId) continue;
    for (const ref of section.refs) {
      deskByRef.set(ref, { id: section.topicId, label: section.label });
    }
  }

  return Response.json({
    fingerprint: briefFingerprint(ids),
    order: briefOrderFingerprint(ids),
    count: rows.length,
    windowLabel,
    level,
    priority,
    customDesks: prefs.customDesks,
    instructions: prefs.instructions,
    coverage,
    sections: plan.sections,
    desks: deskRows,
    sources: briefSourceMap(rows),
    why: briefWhyMap(rows, {
      deskOf: (ref) => deskByRef.get(ref) ?? null,
      isFollowed: signals.isFollowed,
    }),
    followedStories: prefs.followedStories,
    // Offered inside the Desks menu, where the reader already goes to think
    // about desks — never as a notification.
    deskSuggestions: suggestDesks({
      engagedTitles,
      misfiles: prefs.misfiles,
      desks: prefs.desks,
    }),
  });
}

/**
 * External stories considered before ranking. Wider than any level uses, so the
 * "already in your feeds" filter below still has candidates left after it
 * discards the overlap.
 */
const EXTERNAL_CANDIDATE_POOL = 40;

/**
 * Narrow the global external stories down to this user's genuine blind spots.
 *
 * The section's entire claim is "your feeds did not carry this", so a story
 * already sitting in the user's queue has to be dropped — showing it would be
 * both wrong and exactly the duplication clustering exists to remove. Overlap
 * is detected on normalized title shingles, the same cheap signal the
 * clustering pass uses for syndicated copy, which needs no embedding for text
 * the app deliberately never fetched.
 */
function pickExternals(
  externals: {
    title: string;
    url: string;
    outlet: string | null;
    topicId: string | null;
    volume: number;
    sourceCount: number;
  }[],
  /** Every title the scan saw — not just the ones selection kept. A story
   *  sitting unselected in the queue is still not a blind spot. */
  ownedTitles: string[],
  priority: string[],
) {
  if (externals.length === 0) return [];
  const owned = ownedTitles.map((t) => titleShingles(t));
  const followed = new Set(priority);

  return externals
    .filter((e) => {
      const shingles = titleShingles(e.title);
      return !owned.some((o) => jaccard(o, shingles) >= TITLE_SHINGLE_THRESHOLD);
    })
    .map((e) => ({
      title: e.title,
      url: e.url,
      outlet: e.outlet,
      topicId: e.topicId,
      sourceCount: e.sourceCount,
      volume: e.volume,
      // A blind spot on a desk the user actively follows is more worth being
      // told about than one on a desk they never read.
      rank: e.volume + (e.topicId && followed.has(e.topicId) ? 0.5 : 0),
    }))
    .sort((a, b) => b.rank - a.rank);
}

type PostBody = {
  /** A section key from the plan ("lead", "topic:ai", "skip", "external"). */
  section?: string;
  level?: string;
  /** The id-SET fingerprint the client planned against. */
  fingerprint?: string;
  /** The id-ORDER fingerprint — catches a trending re-rank of the same set. */
  order?: string;
  /**
   * Refs an earlier section of this same brief already wrote up.
   *
   * The client sends what the lead actually cited once the lead has finished
   * streaming — planning can only offer the lead a shortlist, never know which
   * of it was chosen. See `coveredRefs` in `brief-plan.ts`.
   */
  covered?: number[];
};

/** Bound the covered list: it is client-supplied and only ever refs. */
const MAX_COVERED_REFS = 40;

function validCovered(v: unknown): number[] {
  if (!Array.isArray(v)) return [];
  return v
    .filter((n): n is number => typeof n === "number" && Number.isInteger(n) && n >= 1)
    .slice(0, MAX_COVERED_REFS);
}

export async function POST(req: Request) {
  let auth;
  try {
    auth = await requireUser();
  } catch {
    return new Response("Unauthorized", { status: 401 });
  }
  const user = auth.user;

  // A sectioned brief is several requests (up to ~8 at the deepest level), and
  // a user may regenerate or retry a section on top of that — hence a ceiling
  // per minute well above the old per-brief one.
  const rl = await checkRateLimit(user.id, "brief", 60, 60);
  if (!rl.allowed) {
    return new Response("Rate limit reached — wait a moment before regenerating the brief.", {
      status: 429,
    });
  }
  const budget = await checkAiBudget(user.id);
  if (!budget.allowed) {
    return new Response(budgetExceededMessage(budget), { status: 429 });
  }

  if (!aiAvailable()) {
    return new Response(
      "No AI provider configured. Add ANTHROPIC_API_KEY or OPENROUTER_API_KEY to your env vars to enable the Daily Brief.",
      { status: 503 },
    );
  }

  let body: PostBody = {};
  try {
    body = (await req.json()) as PostBody;
  } catch {
    // No body or invalid JSON — treat as a default sectioned request.
  }
  return sectionBrief(user.id, body, req);
}

/**
 * Anthropic prompt caching for the article block: a retry of the same section —
 * or the same desk tomorrow, when most of the queue is unchanged — reuses those
 * tokens instead of re-paying for them.
 *
 * Direct Anthropic only, deliberately. The dedicated OpenRouter client DOES
 * forward this as `cache_control`, but OpenRouter fans out to backends with no
 * such concept, and a rejected request would cost the whole section — a bad
 * trade for a discount on the one provider that is already the cheap path here.
 */
function cacheControlFor(resolved: { provider: string }) {
  return resolved.provider === "anthropic"
    ? { providerOptions: { anthropic: { cacheControl: { type: "ephemeral" as const } } } }
    : {};
}

/**
 * Generate one planned section. Small input, capped output: this is the request
 * shape that fits comfortably inside the hosting platform's function budget.
 */
async function sectionBrief(userId: string, body: PostBody, req: Request): Promise<Response> {
  const prefs = await briefPrefs(userId);
  const level = isBriefLevel(body.level) ? body.level : prefs.level;
  const cfg = BRIEF_LEVEL_CONFIG[level];
  const bodyChars = bodyCharLimit(cfg.bodyChars);

  // Re-planned here rather than trusted from the client, so the continuity
  // markers and desk ordering this section is generated under are the same ones
  // the plan endpoint computed — same memory row, same verdicts, same queue.
  // Signals come first because selection itself depends on them: a different
  // weight would select a different queue and shift every `[n]`.
  const [signals, memory] = await Promise.all([
    selectionSignals(userId, prefs),
    loadStoryMemory(userId),
  ]);

  // Plan against the LIGHT rows — no bodies. The queue runs to well over a
  // hundred articles while a section cites at most a dozen, so fetching every
  // body to use ten of them would ship close to a megabyte out of Postgres on a
  // request that also has to run a model call. Bodies come after the section is
  // known, for its refs only.
  const { rows, windowLabel, coverage, scanTitles, threads } = await fetchBriefQueue(userId, {
    limit: queueLimit(cfg.articleLimit),
    scanLimit: scanLimit(cfg.scanLimit, cfg.articleLimit),
    ...signals,
  });
  if (rows.length === 0) {
    return new Response(
      "No unread articles to brief on. Add some feeds and sync them, then come back.",
      { status: 422, headers: { "content-type": "text/plain; charset=utf-8" } },
    );
  }

  const ids = rows.map((r) => r.id);
  const fingerprint = briefFingerprint(ids);
  const order = briefOrderFingerprint(ids);
  // Two ways the queue can move under a half-generated brief, both of which
  // invalidate its [n] numbering: a sync changed the SET, or the trending cron
  // re-ranked the same set. Either way the client re-plans; only the first is
  // ever surfaced to the user as "new articles".
  if (
    (body.fingerprint && body.fingerprint !== fingerprint) ||
    (body.order && body.order !== order)
  ) {
    return Response.json({ error: "queue-changed", fingerprint, order }, { status: 409 });
  }

  const planArticles = toPlanArticles(rows);
  // The external section needs its candidates back to regenerate the same
  // [E n] numbering the plan handed the client. Only fetched when this level
  // actually has that section.
  const externals =
    cfg.externalPicks > 0 && body.section === "external"
      ? pickExternals(
          await loadExternalStories(EXTERNAL_CANDIDATE_POOL).catch(() => []),
          scanTitles,
          prefs.priority,
        )
      : [];

  const covered = validCovered(body.covered);
  const plan = planBrief(planArticles, {
    level,
    priority: prefs.priority,
    externals,
    memory,
    deskWeights: signals.deskWeights,
    desks: prefs.desks,
    threads,
    covered,
  });
  const section = body.section ? findSection(plan, body.section) : plan.sections[0];
  if (!section) {
    return new Response("No such brief section", { status: 404 });
  }

  // Nothing left for this section to write about: everything on the desk was
  // covered in the lead, or the whole queue was written up and the quick-clear
  // list has no leftovers. Answered as an empty section rather than a model
  // call about nothing — the client drops the block, so the reader sees a brief
  // with one fewer heading instead of a heading over an apology.
  if (section.kind !== "external" && section.refs.length === 0) {
    return new Response("", {
      headers: {
        "content-type": "text/plain; charset=utf-8",
        "x-brief-fingerprint": fingerprint,
        "x-brief-order": order,
        "x-brief-section": section.key,
        [EMPTY_SECTION_HEADER]: "1",
      },
    });
  }

  const deskCount = plan.desks.find((d) => d.topicId === section.topicId)?.count;
  const preamble = sectionPreamble(section, {
    windowLabel,
    totalCount: rows.length,
    deskCount,
    scannedCount: coverage.scanned,
  });

  // What the reader already went through today. Only for the sections that
  // write prose about a story: the quick-clear list judges titles in isolation,
  // and the external section is by definition about things NOT in their feeds.
  const wantsReadContext = section.kind === "lead" || section.kind === "topic";
  const readContext = wantsReadContext ? await fetchReadContext(userId, READ_CONTEXT_LIMIT) : [];

  let inputBlock: string;
  if (section.kind === "external") {
    inputBlock = externalBlock(section, prefs.desks);
  } else {
    // Skip works off titles alone, which is what makes covering the whole queue
    // in one call affordable — fetching 120 bodies for it would undo that.
    const bodies =
      section.kind === "skip"
        ? new Map<string, string | null>()
        : await fetchBodies(
            userId,
            section.refs.map((n) => rows[n - 1]?.id).filter((id): id is string => Boolean(id)),
            bodyChars * RAW_FULLTEXT_MULTIPLIER,
          );
    inputBlock = [
      sectionArticleBlock(section, toArticleInputs(rows, section.refs, bodies), level),
      threadBlock(section),
      storyBlock(section),
      continuityBlock(section),
      readContextBlock(readContext),
    ]
      .filter(Boolean)
      .join("\n\n");
  }

  const resolved = await resolveUserSmartModel();
  const baseTokens = sectionMaxTokens(section, level);
  /**
   * One generation attempt. `tuned` carries the reasoning-suppression provider
   * options; the retry drops them so that a backend which rejects the field
   * outright still gets a plain request rather than failing the same way twice.
   */
  const run = (maxTokens: number, tuned: boolean) =>
    streamText({
      model: resolved.model,
      system: sectionSystemPrompt(section, level, {
        readContext: readContext.length > 0,
        continuing: (section.continuing?.length ?? 0) > 0,
        covered: covered.length > 0,
        desks: prefs.desks,
        instructions: prefs.instructions,
      }),
      messages: [
        {
          role: "user",
          content: [
            {
              type: "text",
              text: `Articles for this section:\n${preamble}\n\n${inputBlock}`,
              ...cacheControlFor(resolved),
            },
            { type: "text", text: `Write the "${section.label}" section now.` },
          ],
        },
      ],
      temperature: 0.4,
      // Budget for a thinking pass the section prompt never asked for: on a
      // reasoning model the cap below covers hidden tokens too, and one sized
      // for the prose alone gets spent before the prose starts.
      maxTokens: withReasoningHeadroom(maxTokens, resolved.provider),
      abortSignal: req.signal,
      providerOptions: tuned ? quietReasoningOptions(resolved.provider, resolved.id) : undefined,
    });

  const stream = briefStream(run(baseTokens, true), {
    retry: () => run(retryTokens(baseTokens), false),
    recordUsage: (tokens) => void recordAiUsage(userId, tokens),
    signal: req.signal,
  });
  return new Response(stream, {
    headers: {
      "content-type": "text/plain; charset=utf-8",
      "x-brief-fingerprint": fingerprint,
      "x-brief-order": order,
      "x-brief-section": section.key,
    },
  });
}

/**
 * Output budget for a second attempt at a section whose first attempt produced
 * no visible text at all.
 *
 * The overwhelmingly likely cause is a model that reasoned past even the
 * headroom-adjusted cap, so the one thing worth changing is the ceiling — and
 * changing it by a lot, since a budget that merely doubles a thinking pass's
 * appetite fails the same way. Still bounded: this runs inside the same ~10s
 * function window, and only on the path that would otherwise render nothing.
 */
const EMPTY_RETRY_TOKEN_FLOOR = 2400;

function retryTokens(base: number): number {
  return Math.max(base * 2, EMPTY_RETRY_TOKEN_FLOOR);
}
