/**
 * Planning for a sectioned Daily Brief.
 *
 * ## Why the brief is split into sections
 *
 * This app is hosted on Netlify, where a function is killed at ~10s regardless
 * of what `maxDuration` says (that export is Vercel-only — see the comments in
 * `src/app/api/articles/[id]/simplify/route.ts` and `src/lib/rss/sync.ts`).
 * A single "write me a much more detailed brief" call is exactly the shape that
 * dies there: one long generation, nothing rendered, no partial result.
 *
 * So the brief is planned first — deterministically, with no model involved —
 * into a handful of small sections, and each section is generated by its own
 * short request. Each call reads a bounded slice of the queue and writes a
 * bounded number of tokens, which keeps every request comfortably inside the
 * platform budget while the brief as a whole gets much longer and more
 * detailed than one call could ever produce. A section that fails or times out
 * costs only that section, and can be retried on its own.
 *
 * `refs` are 1-based positions in the article list, so every section cites the
 * same `[n]` numbers and the client can link them to one shared source map.
 *
 * Pure and client-safe: the Today tab uses this to render the section outline
 * before any generation starts.
 */

import {
  OTHER_TOPIC_ID,
  groupByTopic,
  type ClassifiableArticle,
} from "./topics";

export const BRIEF_LEVELS = ["concise", "standard", "deep"] as const;
export type BriefLevel = (typeof BRIEF_LEVELS)[number];
export const DEFAULT_BRIEF_LEVEL: BriefLevel = "standard";

export function isBriefLevel(v: unknown): v is BriefLevel {
  return typeof v === "string" && (BRIEF_LEVELS as readonly string[]).includes(v);
}

export type LevelConfig = {
  label: string;
  /** One line for the depth picker. */
  blurb: string;
  /** How many unread articles the plan considers at all. */
  articleLimit: number;
  /** Plain-text chars per article sent to a desk section. */
  bodyChars: number;
  /** Candidates offered to the lead section… */
  leadCandidates: number;
  /** …and how many of them it should actually write up. */
  leadPicks: number;
  /** Sentences of substance per lead item. */
  leadSentences: number;
  /** Whether lead items get a "Watch:" line. */
  leadWatch: boolean;
  /** Desk sections to generate. */
  maxTopics: number;
  /** Smallest bucket worth its own desk section. */
  minTopicSize: number;
  /** Articles sent to a single desk section (caps that call's input). */
  maxTopicRefs: number;
  /** Bullets requested per desk. */
  topicBullets: number;
  /** Desks get a "Tension:" line where sources cut against each other. */
  topicTension: boolean;
  /** Desks close with an unresolved question. */
  topicOpenQuestion: boolean;
  /** Include the catch-all desk for articles no desk claimed. */
  includeOther: boolean;
  /** Append the low-signal "Quick clear" list. */
  includeSkip: boolean;
};

/**
 * Depth levels. The knobs that grow are per-section (more desks, longer
 * sections) — never "one bigger call", which is the thing the platform can't
 * do. `deep` is ~8 short requests; `concise` is 2.
 */
export const BRIEF_LEVEL_CONFIG: Record<BriefLevel, LevelConfig> = {
  concise: {
    label: "Concise",
    blurb: "The lead and a quick-clear list. Two short passes.",
    articleLimit: 40,
    bodyChars: 700,
    leadCandidates: 8,
    leadPicks: 3,
    leadSentences: 2,
    leadWatch: false,
    maxTopics: 0,
    minTopicSize: 3,
    maxTopicRefs: 6,
    topicBullets: 3,
    topicTension: false,
    topicOpenQuestion: false,
    includeOther: false,
    includeSkip: true,
  },
  standard: {
    label: "Standard",
    blurb: "The lead plus your three busiest desks.",
    articleLimit: 50,
    bodyChars: 900,
    leadCandidates: 10,
    leadPicks: 3,
    leadSentences: 3,
    leadWatch: false,
    maxTopics: 3,
    minTopicSize: 2,
    maxTopicRefs: 8,
    topicBullets: 4,
    topicTension: true,
    topicOpenQuestion: false,
    includeOther: false,
    includeSkip: true,
  },
  deep: {
    label: "Deep",
    blurb: "Every desk with a write-up, tensions and open questions.",
    articleLimit: 60,
    bodyChars: 1300,
    leadCandidates: 12,
    // Three, not four: the lead's ceiling is a time budget (see
    // `sectionMaxTokens`), and a fourth item would come at the cost of the
    // depth each one gets.
    leadPicks: 3,
    leadSentences: 4,
    leadWatch: true,
    maxTopics: 6,
    minTopicSize: 1,
    maxTopicRefs: 10,
    topicBullets: 5,
    topicTension: true,
    topicOpenQuestion: true,
    includeOther: true,
    includeSkip: true,
  },
};

export type SectionKind = "lead" | "topic" | "skip";

export type PlannedSection = {
  /** Stable id the client sends back to generate this one section. */
  key: string;
  kind: SectionKind;
  topicId?: string;
  /** Heading the brief renders for this section. */
  label: string;
  /** The `[n]` numbers this section may cite. */
  refs: number[];
};

export type BriefPlan = {
  level: BriefLevel;
  sections: PlannedSection[];
  /** Every desk found in the queue, including ones this level left out. */
  desks: { topicId: string; label: string; count: number; included: boolean }[];
};

/** What planning needs to know about an article beyond its text. */
export type PlanArticle = ClassifiableArticle & {
  wordCount?: number | null;
  /** Whether the full article body was fetched — a proxy for substance. */
  hasFullText?: boolean;
};

const LEAD_SECTION_LABEL = "The lead";
const SKIP_SECTION_LABEL = "Quick clear";

/** Rough substance signal: a fetched 2000-word essay outranks a 3-line stub. */
function substanceScore(a: PlanArticle): number {
  const words = a.wordCount ?? 0;
  if (words >= 1200) return 2;
  if (words >= 400) return 1;
  if (words > 0) return 0;
  // No word count (most RSS items) — fall back to how much text we have.
  return (a.excerpt ?? "").length >= 400 ? 1 : 0;
}

/**
 * Which articles the lead section gets to choose between. The model picks the
 * final items; this only narrows the candidate set so one call stays small.
 *
 * Preference order: the desks the user cares about, then articles with real
 * body text behind them, then the newest. Returned in ascending `[n]` order so
 * the numbering in the prompt reads naturally.
 */
export function leadCandidateRefs(
  items: PlanArticle[],
  opts: { priority?: string[]; count: number },
): number[] {
  const priority = new Set(opts.priority ?? []);
  const buckets = groupByTopic(items);
  const topicOf = new Map<number, string>();
  for (const b of buckets) for (const ref of b.refs) topicOf.set(ref, b.topicId);

  const scored = items.map((a, i) => {
    const ref = i + 1;
    const onPriorityDesk = priority.has(topicOf.get(ref) ?? "");
    // Recency is a tie-breaker, not a driver: items arrive newest-first, so a
    // shrinking bonus down the list keeps today ahead of last week.
    const recency = items.length > 1 ? (1 - i / (items.length - 1)) * 1.5 : 1.5;
    return {
      ref,
      score:
        (onPriorityDesk ? 3 : 0) +
        (a.hasFullText ? 2 : 0) +
        substanceScore(a) +
        recency,
    };
  });

  return scored
    .sort((a, b) => (b.score !== a.score ? b.score - a.score : a.ref - b.ref))
    .slice(0, Math.max(0, opts.count))
    .map((s) => s.ref)
    .sort((a, b) => a - b);
}

/**
 * Build the section plan for a queue. No model, no network — this runs on every
 * Today load so the page can show the outline (and the desk counts) instantly,
 * then fill each section in.
 */
export function planBrief(
  items: PlanArticle[],
  opts: { level?: BriefLevel; priority?: string[] } = {},
): BriefPlan {
  const level = opts.level ?? DEFAULT_BRIEF_LEVEL;
  const cfg = BRIEF_LEVEL_CONFIG[level];
  const priority = opts.priority ?? [];

  if (items.length === 0) return { level, sections: [], desks: [] };

  const sections: PlannedSection[] = [
    {
      key: "lead",
      kind: "lead",
      label: LEAD_SECTION_LABEL,
      refs: leadCandidateRefs(items, { priority, count: cfg.leadCandidates }),
    },
  ];

  const buckets = groupByTopic(items, { priority });
  const eligible = buckets.filter(
    (b) =>
      b.refs.length >= cfg.minTopicSize && (b.topicId !== OTHER_TOPIC_ID || cfg.includeOther),
  );
  const chosen = eligible.slice(0, cfg.maxTopics);
  const chosenIds = new Set(chosen.map((b) => b.topicId));

  for (const b of chosen) {
    sections.push({
      key: `topic:${b.topicId}`,
      kind: "topic",
      topicId: b.topicId,
      label: b.label,
      refs: b.refs.slice(0, cfg.maxTopicRefs),
    });
  }

  if (cfg.includeSkip) {
    sections.push({
      key: "skip",
      kind: "skip",
      label: SKIP_SECTION_LABEL,
      // Titles only, so the whole queue fits in one small call.
      refs: items.map((_, i) => i + 1),
    });
  }

  return {
    level,
    sections,
    desks: buckets.map((b) => ({
      topicId: b.topicId,
      label: b.label,
      count: b.refs.length,
      included: chosenIds.has(b.topicId),
    })),
  };
}

/** Look a section up in a plan by the key the client sent. */
export function findSection(plan: BriefPlan, key: string): PlannedSection | null {
  return plan.sections.find((s) => s.key === key) ?? null;
}

/**
 * Identity of the *settings* a stored brief was generated under. Paired with
 * the unread-set fingerprint, this is what tells us a stored brief no longer
 * matches what the user has asked for (they switched to Deep, or changed which
 * desks they follow) and should be regenerated.
 */
export function briefSettingsKey(level: BriefLevel, priority: string[]): string {
  return `sectioned/v1/${level}/${[...priority].join(",")}`;
}
